# SPDX-License-Identifier: GPL-2.0-or-later
name: cross

on: [push, pull_request]

jobs:
  arch:
    strategy:
      fail-fast: false
      matrix:
        arch: ["m68k", "s390x", "sparc64"]
    uses: ./.github/workflows/arch.yml
    with:
      arch: ${{ matrix.arch }}
